// Script para sembrar datos de ejemplo en modo demo
// Ejecutar: pnpm tsx scripts/seed-demo.ts
// O usar la API directamente

export const personasDemo = [
  {
    nombre: 'María',
    apellido: 'García López',
    edad: 35,
    genero: 'femenino',
    ultimaUbicacion: 'Barrio San Antonio, Cali',
    fechaDesaparicion: '2026-08-10',
    descripcion: 'Mujer de contextura delgada, cabello castaño, vestía camiseta blanca y pantalón jeans. Llevaba bolso negro.',
    reportanteNombre: 'Juan García',
    reportanteTelefono: '3001234567',
    reportanteRelacion: 'hermano-hermana',
  },
  {
    nombre: 'Carlos',
    apellido: 'Pérez Mendoza',
    edad: 42,
    genero: 'masculino',
    ultimaUbicacion: 'Comuna 20, Cali',
    fechaDesaparicion: '2026-08-10',
    descripcion: 'Hombre alto, barba, camiseta azul, jeans. Tiene tatuaje en el brazo derecho.',
    reportanteNombre: 'Ana Pérez',
    reportanteTelefono: '3209876543',
    reportanteRelacion: 'esposo-esposa',
  },
  {
    nombre: 'Lucía',
    apellido: 'Rodríguez',
    edad: 28,
    genero: 'femenino',
    ultimaUbicacion: 'Chocó, Pereira',
    fechaDesaparicion: '2026-08-10',
    descripcion: 'Mujer joven, cabello largo negro, vestía vestido floral.',
    reportanteNombre: 'Pedro Rodríguez',
    reportanteTelefono: '3151122334',
    reportanteRelacion: 'madre-padre',
  },
  {
    nombre: 'Andrés',
    apellido: 'Martínez',
    edad: 8,
    genero: 'masculino',
    ultimaUbicacion: 'Centro, Cali',
    fechaDesaparicion: '2026-08-10',
    descripcion: 'Niño de 8 años, cabello corto, vestía uniforme escolar azul.',
    reportanteNombre: 'Laura Martínez',
    reportanteTelefono: '3005567890',
    reportanteRelacion: 'madre-padre',
  },
  {
    nombre: 'José',
    apellido: 'Hernández',
    edad: 67,
    genero: 'masculino',
    ultimaUbicacion: 'Barrio La Flora, Cali',
    fechaDesaparicion: '2026-08-10',
    descripcion: 'Adulto mayor, lleva bastón, camisa a cuadros.',
    reportanteNombre: 'María Hernández',
    reportanteTelefono: '3014455667',
    reportanteRelacion: 'hijo-hija',
  },
];

export const centrosDemo = [
  {
    nombre: 'Centro Comunitario San Antonio',
    direccion: 'Calle 5 #12-34',
    ciudad: 'Cali',
    necesidades: 'Agua potable, alimentos no perecederos, medicamentos, cobijas',
    horarios: '8:00 AM - 8:00 PM',
    telefono: '6025551234',
    whatsapp: '573005551234',
  },
  {
    nombre: 'Iglesia Santa María',
    direccion: 'Carrera 10 #5-20',
    ciudad: 'Cali',
    necesidades: 'Agua, alimentos, ropa en buen estado',
    horarios: '24 horas',
    telefono: '6025555678',
  },
  {
    nombre: 'Centro de Acopio Cruz Roja',
    direccion: 'Av. 3 Norte #15-50',
    ciudad: 'Cali',
    necesidades: 'Botiquines, agua embotellada, comida enlatada',
    horarios: '7:00 AM - 10:00 PM',
    telefono: '132',
    whatsapp: '573001321234',
  },
  {
    nombre: 'Punto de Ayuda Quindío',
    direccion: 'Plaza de Bolívar, Armenia',
    ciudad: 'Quindío',
    necesidades: 'Ropa, alimentos, artículos de higiene',
    horarios: '9:00 AM - 6:00 PM',
    telefono: '6067412345',
  },
];

export const alberguesDemo = [
  {
    nombreVoluntario: 'María Fernanda Castro',
    telefono: '3001234567',
    whatsapp: '573001234567',
    direccion: 'Carrera 15 #8-23, San Juan Bosco',
    ciudad: 'Cali',
    capacidad: 12,
    servicios: 'Hospedaje, alimentación básica, baño',
    reglas: 'No fumar dentro de la casa. Llegar antes de las 9 PM.',
  },
  {
    nombreVoluntario: 'Roberto Salazar',
    telefono: '3109876543',
    direccion: 'Calle 34 #56-78',
    ciudad: 'Pereira',
    capacidad: 6,
    servicios: 'Hospedaje, agua, energía',
    reglas: 'No mascotas. Familias优先.',
  },
  {
    nombreVoluntario: 'Ana Lucía Vargas',
    telefono: '3157654321',
    whatsapp: '573157654321',
    direccion: 'Centro, Armenia',
    ciudad: 'Quindío',
    capacidad: 8,
    servicios: 'Hospedaje, comida, primeros auxilios básicos',
    reglas: 'Solo familias con niños. Sin mascotas.',
  },
];
